name: Thesis PDF

# Start job on every PR, and whenever .tex, .sty, 
# or the workflow itself has changed on master.
on:
  push:
    branches: [ master ]
    paths: [ '**.tex', '**.sty', '.github/workflows/**.yml' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
    - name: Checkout Project
      uses: actions/checkout@v2
      with:
        # Graphics managed using git-lfs should be downloaded for usage in tex
        lfs: true

    # Compile the thesis using the existing latex-action from xu cheng
    - name: LaTeX compilation
      uses: xu-cheng/latex-action@1.2.1
      with:
        root_file: main.tex
        args: -cd -use-make -pdf -file-line-error -interaction=nonstopmode -shell-escape

    # Publish the resulting 'main.pdf' file as an artifact of the build job
    - name: Publish the generated PDF file as an artifact
      uses: actions/upload-artifact@v1
      with:
        name: main.pdf
        path: main.pdf
