# This is a basic workflow to help you get started with Actions

name: Thesis PDF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: [ '**.tex', '**.sty', '.github/workflows/**.yml' ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Project
      uses: actions/checkout@v2
      with:
        # Graphics managed using git-lfs should be downloaded for usage in tex
        lfs: true

    - name: LaTeX compilation
      uses: xu-cheng/latex-action@1.2.1
      with:
        # The root LaTeX file to be compiled
        root_file: main.tex
        args: -cd -use-make -pdf -file-line-error -interaction=nonstopmode -shell-escape

    - name: Publish the generated PDF file as an artifact
      uses: actions/upload-artifact@v1
      with:
        name: main.pdf
        path: main.pdf
